dashboard/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
	url(r'^$', index, name='index'),
]

ppw_tugas1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import dashboard.urls as dashboard
import add_friend.urls as add_friend
import halaman_profile.urls as halaman_profile
import update_status.urls as update_status

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include(dashboard, namespace='dashboard')),
    url(r'^add-friend/', include(add_friend, namespace='add-friend')),
    url(r'^halaman-profile/', include(halaman_profile, namespace='halaman-profile')),
    url(r'^update-status/', include(update_status, namespace='update-status')),
    url(r'^$', RedirectView.as_view(url='/update-status/', permanent='True'), name='index'),
]

templates/partials/footer.html
<!--<p class="modal-footer" 
style="
left: 0;
bottom: 0;
width: 100%;
background-color: white;
color: black;
text-align: center;">&copy; Made with Blood, Sweat, &amp; Tears by {{author}}</p>-->
<div>
	<p align="center">&copy; Created with blood, sweat, &amp; tears by {{ author }}</p>
</div>

templates/partials/header.html
<nav class="navbar navbar-default navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed"
			data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>

			<!-- Kalo mencet logo LingIn (home) redirect ke Profile -->
			<a class="navbar-brand" href="{% url 'halaman-profile:index' %}" style="padding-bottom: 15px; padding-top: 5px; ">Ling <img src="https://seeklogo.com/images/L/linkedin-icon-logo-05B2880899-seeklogo.com.png" width="40px" height="40px">
			</a>
		</div>
		<div id="navbar" class="navbar-collapse collapse">
			<ul class="nav navbar-nav navbar-right">
				<li><a href="{% url 'update-status:index' %}" style="color: black"><i class="fa fa-pencil fa-1g" aria-hidden="true"></i></a></li>
				<li><a href="{% url 'add-friend:index' %}" style="color: black"><i class="fa fa-users" aria-hidden="true"></i></a></li>
				<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#" style="color: black; padding-top: 13px;"><img src="https://image.ibb.co/b7nmvb/great_background_of_blonde_woman_laughing_23_2147631737.jpg" style="border-radius: 50%; display: block; margin: 0 auto; float: left; margin-right: 5px;" width="27px" height="27px"></i>
				<ul class="dropdown-menu">
				<li><a href="{% url 'halaman-profile:index' %}" style="color: black;"><i class="fa fa-user-circle" aria-hidden="true"></i> My Profile</a></li>
          		<li><a href="{% url 'dashboard:index' %}" style="color: black;"><i class="fa fa-bar-chart" aria-hidden="true"></i> Stats</a></li>
        		</ul>
      			</li>
			</ul>
		</div> <!--/.nav-collapse -->
	</div>
</nav>