dashboard/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
	url(r'^$', index, name='index'),
]

ppw_tugas1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import dashboard.urls as dashboard
import add_friend.urls as add_friend
import halaman_profile.urls as halaman_profile
import update_status.urls as update_status

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include(dashboard, namespace='dashboard')),
    url(r'^add-friend/', include(add_friend, namespace='add-friend')),
    url(r'^halaman-profile/', include(halaman_profile, namespace='halaman-profile')),
    url(r'^update-status/', include(update_status, namespace='update-status')),
    url(r'^$', RedirectView.as_view(url='/update-status/', permanent='True'), name='index'),
]

update_status/urls.py
from django.conf.urls import url
from .views import index, status_post

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_status', status_post, name='add_status')
]

update_status/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    status = models.TextField(max_length=500)
    created_date = models.DateTimeField(auto_now_add=True)

update_status/forms.py
from django import forms

class UpdateStatus_Form(forms.Form):
	error_messages = {
		'required': 'Please enter this input',
		'invalid': 'Isi input ini dengan status',
	}
	attrs = {
		'class': 'form-control',
		'placeholder' : "Write your thoughts here..",
		'rows' : 6,
		'cols' : 25
	}

	status = forms.CharField(label='', required=True, max_length=500, widget=forms.Textarea(attrs=attrs))

update_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import UpdateStatus_Form
from .models import Status
from halaman_profile.models import AccountProfile

# Create your views here.
response = {'author': "Kelompok 4 PPW-F"}

def index(request):
	html = 'update_status.html'
	response['name'] = AccountProfile.objects.get(id=1)
	status = Status.objects.all()
	response['status'] = status
	response['updatestatus_form'] = UpdateStatus_Form
	return render(request, html, response)

def status_post(request):
	form = UpdateStatus_Form(request.POST)
	if request.method == 'POST' and form.is_valid():
		response['status'] = request.POST['status'] #if request.POST['name'] != ""
		status = Status(status=response['status'])
		status.save()
		html = 'update_status.html'
		render(request, html, response)
		return HttpResponseRedirect('/update-status/')
	else:
		return HttpResponseRedirect('/update-status/')

update_status/templates/update_status.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block title %} LingIn: Update Status {% endblock %}
{% block content %}
    <section name="status-input" id="status-input">
    	<div>
    		<form id="form" method="POST" action="{% url 'update-status:add_status' %}">
    			<h2>What's happening?</h2>
    			<br>
    			{% csrf_token %}
    			{{ updatestatus_form.status }}
    			<br>
    			<input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Post">
    			<br>
    		</form>
    	</div>
    </section>
	<h3 style="text-align: center; font-family: Open Sans; font-weight: bold;">{{ name }}'s Posts</h3>
	<hr>
	<section name="status">
		<div class="container">
			<div class="flex">
				{% if status %}
					{% for data in status reversed %}
						<div class="flex-item">
							<div class="row">
								<div class="col-sm-1"></div>
								<div class="col-sm-1">
									<div class="display-picture">
										<img src="https://image.ibb.co/b7nmvb/great_background_of_blonde_woman_laughing_23_2147631737.jpg" style="border-radius: 50%; display: block; margin: 0 auto" width="70px" height="70px">
									</div>
								</div>
								<div class="col-sm-9">
										<div class="author-name" style="font-family: Open Sans; font-weight: bold;">
											<a href="/halaman-profile/">{{ name }}</a>
										</div>
										<div class="status-message">
											{{ data.status }}
										</div>
										<div class="date-created" style="font-family: Open Sans; font-weight: bold;">
											{{ data.created_date }}
										</div>
								</div>
								<div class="col-sm-1"></div>
							</div>
						</div>
					{% endfor %}
				{% else %}
					<div class="empty-message">
						<p style="font-weight: bold; font-size: 20px; margin-left: 20px;">You haven't posted anything. Start to post one!</p>
					</div>
					<br>
				{% endif %}
			</div>
		</div>
	</section>

	<br>
	<br>
	<br>
{% endblock %}