add_friend/urls.py
from django.conf.urls import url
from .views import index, add_friend, delete_friend

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_friend', add_friend, name='add_friend'),
	url(r'^(?P<id>[0-9]+)/delete/$', delete_friend, name='delete_friend'),
]

dashboard/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
	url(r'^$', index, name='index'),
]

ppw_tugas1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import dashboard.urls as dashboard
import add_friend.urls as add_friend
import halaman_profile.urls as halaman_profile
import update_status.urls as update_status

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include(dashboard, namespace='dashboard')),
    url(r'^add-friend/', include(add_friend, namespace='add-friend')),
    url(r'^halaman-profile/', include(halaman_profile, namespace='halaman-profile')),
    url(r'^update-status/', include(update_status, namespace='update-status')),
    url(r'^$', RedirectView.as_view(url='/update-status/', permanent='True'), name='index'),
]

add_friend/models.py
from django.db import models
from django.utils import timezone
import pytz

class NewFriend(models.Model):
    name = models.CharField(max_length=27)
    url = models.URLField()
    created_date = models.DateTimeField(auto_now_add=timezone.now())

add_friend/forms.py
from django import forms

class Friend_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    name_attrs = { 
        'type': 'text',
        'class': 'form-control',
        'placeholder':'Abraham Lincoln'
    }
    url_attrs = {
        'type': 'text',
        'cols': 50, 
        'rows': 4,
        'class': 'form-control',
        'placeholder':'thisisabraham.herokuapp.com'
    }

    name = forms.CharField(label='Friend Name:', required=False, max_length=27, widget=forms.TextInput(attrs=name_attrs))
    url = forms.URLField(label ='Friend URL:',required=True ,widget=forms.TextInput(attrs=url_attrs))

add_friend/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import NewFriend
from .forms import Friend_Form
from datetime import datetime
from django.http import HttpResponseRedirect
from halaman_profile.models import AccountProfile

# Create your views here.
response = {'author': "Kelompok 4 PPW-F"}

def index(request):
	html = 'add_friend.html'
	response['name'] = AccountProfile.objects.get()
	friends = NewFriend.objects.all()
	response['friends'] = friends
	response['friend_form'] = Friend_Form
	return render(request, html, response)
	
def add_friend(request):
	form = Friend_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['name'] = request.POST['name']
		response['url'] = request.POST['url']
		new_friend = NewFriend(name=response['name'],url=response['url'])
		new_friend.save()
		return HttpResponseRedirect('/add-friend/')
	else:
		return HttpResponseRedirect('/add-friend/')

def delete_friend(request, id=None):
	obj = get_object_or_404(NewFriend, pk=id)
	obj.delete()
	return HttpResponseRedirect('/add-friend/')

add_friend/templates/add_friend.html
{% extends "base.html" %}
{% block title %} LingIn: Friend List {% endblock %}
{% block content %}
<h2 style="text-align: center; margin-top: 30px; font-family: Open Sans; font-weight: bold;">{{ name }}'s Friends List</h2>
<hr/>
<section name="status-input" id="status-input">
    <div class="container">
        <form id="form" method="POST" action="{% url 'add-friend:add_friend' %}">
            <h3 style="font-family: Open Sans; font-weight: bold;" ><i class="fa fa-user-plus" aria-hidden="true"></i> Add New Friend</h3>
            <hr>
            {% csrf_token %}
            {{ friend_form }}
            <br>
            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Add Friend">
        </form>
    </div>
</section>
<br>
<br>
<section name="my-list" id="my-list">
    <div class="flex-addfriend">
        {% if friends %}
            {% for friend in friends %}
                <div class="flex-friend-item">
                    <div class="to-do-list">
                        <div class="to-do-list-title">
                            {{friend.name}}
                        </div>
                        <div class="to-do-list-date-added">
                             Added {{friend.created_date}}
                        </div>
                        <div class="friend-display-picture">
                            <img src="https://cdn.vectorstock.com/i/thumb-large/27/13/14292713.jpg" style="border-radius: 50%;" width="125px" height="125px" align="center">
                        </div>
                        <div class="to-do-list-description">
                            <a href="http://{{ all_friends.url }}/">{{friend.url}}</a>
                        </div>
                        <div class="to-do-list-delete">
                            <a style="text-decoration: none; color: white" href="{% url 'add-friend:delete_friend' friend.id %}"><div class="to-do-list-delete-button" data-id="{{friend.id}}"><i class="fa fa-times" aria-hidden="true"></i> Unfriend</div>
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
        <div class="alert alert-danger text-center">
            <strong>Sorry!</strong> You dont have friends.
        </div>
        {% endif %}
    </div>
</section>
<br>
{% endblock %}